### PR TITLE
[ECC chip] Fixed- and variable-base scalar multiplication

### LINKED ISSUE #38: Implement generic ECC gadget
Specifically we want something that is generic over a (j = 0) curve. We need:

- In-circuit point representations.
- Complete point addition
- Scalar multiplication (which internally will use incomplete addition, not the above APIs)

### PR DESCRIPTION
**Pull request by therealyingtong**
Closes #38.

### CODE REVIEW

File: src/circuit/gadget/ecc/chip/witness_scalar_fixed/short.rs [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    pub fn create_gate(&self, meta: &mut ConstraintSystem<C::Base>) {
+        // Check that sign is either 1 or -1.
+        meta.create_gate("check sign", |meta| {
+            let q_scalar_fixed_short = meta.query_selector(self.q_scalar_fixed_short);
+            let sign = meta.query_advice(self.super_config.window, Rotation::cur());
+
+            vec![
+                q_scalar_fixed_short
+                    * (sign.clone() + Expression::Constant(C::Base::one()))
+                    * (sign - Expression::Constant(C::Base::one())),
```
Comment (therealyingtong) [inline src/circuit/gadget/ecc/chip/witness_scalar_fixed/short.rs:35]: Simpler might be `q_scalar_fixed_short * (sign.clone() * sign.clone() - Expression::Constant(C::Base::one()))` (aka check that the sign bit squared equals one)

_Originally posted by @ebfull in https://github.com/zcash/orchard/pull/107#discussion_r647654106_

File: src/circuit/gadget/ecc/chip.rs [hunk 2]
```diff
@@ -202,26 +239,45 @@ where
...
+            |mut region| {
+                let cell = region.assign_advice(
+                    || "Scalar var",
+                    self.config().advices[0],
+                    0,
+                    || value.ok_or(Error::SynthesisError),
+                )?;
+                Ok(CellValue::new(cell, value))
+            },
+        )
```
Comment (therealyingtong) [inline src/circuit/gadget/ecc/chip.rs:256]: Unresolved comment: https://github.com/zcash/orchard/pull/73#discussion_r640939832

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 3]
```diff
@@ -0,0 +1,472 @@
...
+    fn create_final_scalar_gate(&self, meta: &mut ConstraintSystem<C::Base>) {
+        meta.create_gate("Decompose scalar for variable-base mul", |meta| {
+            let q_mul_decompose_var = meta.query_selector(self.q_mul_decompose_var);
+            let scalar = meta.query_advice(self.scalar, Rotation::cur());
+            let z_cur = meta.query_advice(self.z_complete, Rotation::cur());
+
+            // The scalar field `F_q = 2^254 + t_q`.
+            // -((2^127)^2) = -(2^254) = t_q (mod q)
+            let t_q = -(C::Scalar::from_u128(1u128 << 127).square());
+            let t_q = C::Base::from_bytes(&t_q.to_bytes()).unwrap();
```
Comment (therealyingtong) [inline src/circuit/gadget/ecc/chip/mul.rs:109]: TODO: add `t_q` (and corresponding `t_p` for Pallas) as constants.

_Originally posted by @therealyingtong in https://github.com/zcash/orchard/pull/107#discussion_r646072661_

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 4]
```diff
@@ -0,0 +1,529 @@
...
+        region: &mut Region<'_, pallas::Base>,
+        offset: usize,
+        mut acc: EccPoint,
+        base: OrchardFixedBases,
+        scalar: &ScalarFixed,
+    ) -> Result<EccPoint, Error> {
+        // This is 2^w, where w is the window width
+        let h = pallas::Scalar::from_u64(constants::H as u64);
+
+        let base_value = base.generator();
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:361]: Likewise here:
image

This is because... (see next comment)

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 5]
```diff
@@ -0,0 +1,529 @@
...
+    }
+}
+
+impl OrchardFixedBases {
+    pub fn generator(self) -> pallas::Affine {
+        match self {
+            Self::ValueCommitV => constants::value_commit_v::generator(),
+            Self::Full(base) => {
+                let base: OrchardFixedBase = base.into();
+                base.generator
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:52]: The `base.into()` here computes the lagrange coefficients inline:
https://github.com/zcash/orchard/blob/37b1b7f357cd34d93f9c55bb96efd05ab4e84408/src/constants/load.rs#L24-L61
But we then immediately discard them and just return the generator itself. Instead, add a `generator()` method to `OrchardFixedBasesFull` which can sidestep deriving the entire `OrchardFixedBase`.

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 6]
```diff
@@ -0,0 +1,529 @@
...
+            )?;
+            let y = CellValue::new(y_cell, y);
+
+            EccPoint { x, y }
+        };
+
+        // Assign u = (y_p + z_w).sqrt() for `m0`
+        {
+            let k0 = scalar.windows_usize()[0];
+            let u0 = &base.u()[0];
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:323]: Same thing happens twice here (inside `base.generator()` and `base.u()`):
image

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 7]
```diff
@@ -0,0 +1,529 @@
...
+            }
+        }
+    }
+
+    pub fn u(self) -> Vec<WindowUs> {
+        match self {
+            Self::ValueCommitV => ValueCommitV::get().u_short.0.as_ref().to_vec(),
+            Self::Full(base) => {
+                let base: OrchardFixedBase = base.into();
+                base.u.0.as_ref().to_vec()
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:62]: So let's also add an `OrchardFixedBasesFull::u` method to use here.

**Review by str4d — COMMENTED** [review]
Found some easy performance wins!

File: src/circuit/gadget/ecc/chip.rs [hunk 8]
```diff
@@ -66,28 +72,44 @@ pub struct EccConfig {
...
+    /// Selector used in scalar decomposition for variable-base scalar mul
+    pub q_init_z: Selector,
     /// Variable-base scalar multiplication (final scalar)
-    pub q_mul_complete: Selector,
+    pub q_mul_z: Selector,
+    /// Variable-base scalar multiplication (overflow check)
+    pub q_mul_overflow: Selector,
+    // Fixed column to constrain s_{120..=125} of s = alpha + k_{254} * 2^127
+    pub q_three_bit: Selector,
+    // Fixed column to constrain s_{126} of s = alpha + k_{254} * 2^127
```
Comment (daira) [inline src/circuit/gadget/ecc/chip.rs:93]: It's simpler to treat the value as as being 130 bits rather than 127 bits, so that we don't need to special-case the top element. I've described this at https://hackmd.io/o9EzZBwxSWSi08kQ_fMIOw?both#Overflow-check-for-variable-base-scalar-multiplication .

File: src/circuit/gadget/ecc/chip.rs [hunk 9]
```diff
@@ -66,28 +72,44 @@ pub struct EccConfig {
...
+    pub q_one_bit: Selector,
```
Comment (daira) [inline src/circuit/gadget/ecc/chip.rs:94]: It's simpler to treat the value as as being 130 bits rather than 127 bits, so that we don't need to special-case the top element. I've described this at https://hackmd.io/o9EzZBwxSWSi08kQ_fMIOw?both#Overflow-check-for-variable-base-scalar-multiplication .

```suggestion
```

File: src/circuit/gadget/ecc/chip.rs [hunk 10]
```diff
@@ -138,13 +164,18 @@ impl EccChip {
             q_mul_hi: meta.selector(),
             q_mul_lo: meta.selector(),
             q_mul_decompose_var: meta.selector(),
-            q_mul_complete: meta.selector(),
+            q_init_z: meta.selector(),
+            q_mul_z: meta.selector(),
+            q_mul_overflow: meta.selector(),
+            q_three_bit: meta.selector(),
+            q_one_bit: meta.selector(),
```
Comment (daira) [inline src/circuit/gadget/ecc/chip.rs:171]:
```suggestion
```

File: src/circuit/gadget/ecc/chip/mul/overflow.rs [hunk 11]
```diff
@@ -0,0 +1,401 @@
...
+
+pub struct Config {
+    // Selector to check decomposition of lsb
+    q_mul_z: Selector,
+    // Selector to check z_0 = alpha + t_q (mod p)
+    q_mul_overflow: Selector,
+    // Selector to constrain s_{120..=125} of s = alpha + k_{254} * 2^127
+    q_three_bit: Selector,
+    // Selector to constrain s_{126} of s = alpha + k_{254} * 2^127
+    q_one_bit: Selector,
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/overflow.rs:26]:
```suggestion
```

File: src/circuit/gadget/ecc/chip/mul/overflow.rs [hunk 12]
```diff
@@ -0,0 +1,401 @@
...
+    perm: Permutation,
+}
+
+impl From<&EccConfig> for Config {
+    fn from(ecc_config: &EccConfig) -> Self {
+        Self {
+            q_mul_z: ecc_config.q_mul_z,
+            q_mul_overflow: ecc_config.q_mul_overflow,
+            q_three_bit: ecc_config.q_three_bit,
+            q_one_bit: ecc_config.q_one_bit,
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/overflow.rs:41]:
```suggestion
```

File: src/circuit/gadget/ecc/chip/mul/overflow.rs [hunk 13]
```diff
@@ -0,0 +1,401 @@
...
+            let z_prev = meta.query_advice(self.lookup_config.running_sum, Rotation::prev());
+            let z_cur = meta.query_advice(self.lookup_config.running_sum, Rotation::cur());
+
+            // z_cur = (z_prev - word) / (2)
+            // word = z_prev - z_cur * 2
+            let one_bit_value = z_prev - z_cur * pallas::Base::from_u64(2);
+
+            let one = Expression::Constant(pallas::Base::one());
+            vec![q_one_bit * one_bit_value.clone() * (one - one_bit_value)]
+        });
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/overflow.rs:133]:
```suggestion
```

File: src/circuit/gadget/ecc/chip/mul/overflow.rs [hunk 14]
```diff
@@ -0,0 +1,401 @@
...
+                        // s_{126}
+                        let s_126 = pallas::Base::from_u64(leftover_bits[6] as u64);
+
+                        (Some(lo_three), Some(hi_three), Some(s_126))
+                    } else {
+                        (None, None, None)
+                    }
+                };
+
+                // Subtract s_{120..=122}
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/overflow.rs:328]: All of this goes away (and we check 130 bits).

File: src/circuit/gadget/ecc/chip.rs [hunk 15]
```diff
@@ -202,26 +239,45 @@ where
 
     fn witness_scalar_var(
         &self,
-        _layouter: &mut impl Layouter<C::Base>,
-        _value: Option<C::Base>,
+        layouter: &mut impl Layouter<C::Base>,
+        value: Option<C::Base>,
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip.rs]: Yes, the correctness argument would need to be re-checked if it were applied to Vesta.

File: src/circuit/gadget/ecc/chip/mul/overflow.rs [hunk 16]
```diff
@@ -0,0 +1,244 @@
...
+        // s = alpha + k_254 ⋅ 2^130 is witnessed here, and then copied into
+        // the decomposition as well as the overflow check gate.
+        // In the overflow check gate, we check that s is properly derived
+        // from alpha and k_254.
+        let s = {
+            let k_254 = *zs[254];
+            let s_val = alpha
+                .value()
+                .zip(k_254.value())
+                .map(|(alpha, k_254)| alpha + k_254 * pallas::Base::from_u128(1 << 65).square());
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/overflow.rs:114]: https://github.com/zcash/pasta_curves/issues/14

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 17]
```diff
@@ -0,0 +1,426 @@
...
+const INCOMPLETE_LO_RANGE: Range<usize> = (INCOMPLETE_LEN / 2)..INCOMPLETE_LEN;
+
+// Bits k_{3} to k_{1} inclusive are used in complete addition.
+// Bit k_{0} is handled separately.
+const COMPLETE_RANGE: Range<usize> = INCOMPLETE_LEN..(INCOMPLETE_LEN + NUM_COMPLETE_BITS);
+
+pub struct Config {
+    // Selector used to constrain the initialization of the running sum to be zero.
+    q_init_z: Selector,
+    // Selector used to check z_0 = 2*z_1 + k_0
```
Comment (ebfull) [inline src/circuit/gadget/ecc/chip/mul.rs:39]: Should be `z_i = 2*z_{i+1} + k_i`

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 18]
```diff
@@ -0,0 +1,426 @@
...
+        };
+        let y_p = if let Some(lsb) = lsb {
+            if !lsb {
+                base.y.value().map(|y_p| -y_p)
+            } else {
+                Some(pallas::Base::zero())
+            }
+        } else {
+            None
+        };
```
Comment (ebfull) [inline src/circuit/gadget/ecc/chip/mul.rs:285]: Nothing is constraining that this value (witnessed by the prover) is the correct value -- which should be Acc - P or Acc depending on the value of `lsb`, so there's a missing gate here.

**Review by ebfull — CHANGES_REQUESTED** [review]

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 19]
```diff
@@ -0,0 +1,426 @@
...
+                let acc = self
+                    .add_config
+                    .assign_region(&base, &base, offset, &mut region)?;
+
+                // Increase the offset by 1 after complete addition.
+                let offset = offset + 1;
+
+                // Initialize the running sum for scalar decomposition to zero
+                let z_init = {
+                    // Constrain the initialization of `z` to equal zero.
```
Comment (ebfull) [inline src/circuit/gadget/ecc/chip/mul.rs:131]: Let's make a TODO to enforce this to equal zero via public inputs or something (using permutation argument).

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 20]
```diff
@@ -0,0 +1,427 @@
...
+        // Increase the offset by 1 after initializing `z`.
+        let offset = offset + 1;
+
+        // Double-and-add (incomplete addition) for the `hi` half of the scalar decomposition
+        let (x_a, y_a, zs_incomplete_hi) = self.hi_config.double_and_add(
+            region,
+            offset,
+            &base,
+            bits_incomplete_hi,
+            (X(acc.x), Y(acc.y.value()), z_init),
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul.rs]: We don't use `acc.y.cell()` anywhere, so we aren't constraining the output of the initial complete addition to be the input to the incomplete addition. We need to pass `acc.y` in entirely, and then inside `double_and_add` have the initial values of lambda_1 etc. be appropriately constrained.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 21]
```diff
@@ -0,0 +1,427 @@
...
+        )?;
+
+        // Double-and-add (incomplete addition) for the `lo` half of the scalar decomposition
+        let z = &zs_incomplete_hi[zs_incomplete_hi.len() - 1];
+        let (x_a, y_a, zs_incomplete_lo) = self.lo_config.double_and_add(
+            region,
+            offset,
+            &base,
+            bits_incomplete_lo,
+            (x_a, y_a, *z),
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul.rs]: Similarly, `hi_config.double_and_add` is only returning the value of the intermediate `y_a`, not an assigned cell that can be constrained into `lo_config.double_and_add` to connect them together. If `double_and_add` assigns its final `y_a`, then we can just pass that in here as we would with `acc.y` above.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 22]
```diff
@@ -0,0 +1,427 @@
...
+        let offset = offset + INCOMPLETE_LO_RANGE.len() + 2;
+
+        // Complete addition
+        let (acc, zs_complete) = {
+            let z = &zs_incomplete_lo[zs_incomplete_lo.len() - 1];
+            let complete_config: complete::Config = self.into();
+            // Bits used in complete addition. k_{3} to k_{1} inclusive
+            // The LSB k_{0} is handled separately.
+            let bits_complete = &bits[COMPLETE_RANGE];
+            complete_config.assign_region(region, offset, bits_complete, base, x_a, y_a, *z)?
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul.rs]: This is assigning `y_a` to a cell internally, but isn't connecting it to the incomplete addition output (because as above, `double_and_add` only returns a value). Once `double_and_add` returns a `CellValue`, we can just pass that in here and copy it into the complete addition.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs [hunk 23]
```diff
@@ -0,0 +1,296 @@
...
+                self.x_p,
+                row + offset,
+                || x_p.ok_or(Error::SynthesisError),
+            )?;
+            region.assign_advice(
+                || "y_p",
+                self.y_p,
+                row + offset,
+                || y_p.ok_or(Error::SynthesisError),
+            )?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul/incomplete.rs:254]: This causes a double-assignment in the circuit, due to sharing these columns between `hi_config` and `lo_config`. This is fine, as we pass the same `base` into both `incomplete_addition` invocations.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs [hunk 24]
```diff
@@ -0,0 +1,296 @@
...
+                    lambda1_cur.clone() * lambda1_cur.clone() - x_a_cur.clone() - x_p_cur.clone();
+                lambda_neg * (x_a_cur.clone() - lambda1_expr)
+                    - Expression::Constant(pallas::Base::from_u64(2)) * y_a_cur.clone()
+            };
+
+            // λ_{2,i}^2 − x_{A,i+1} −(λ_{1,i}^2 − x_{A,i} − x_{P,i}) − x_{A,i} = 0
+            let poly3 = lambda2_cur.clone() * lambda2_cur.clone()
+                - x_a_next.clone()
+                - (lambda1_cur.clone() * lambda1_cur)
+                + x_p_cur;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul/incomplete.rs:154]:
```suggestion
            let secant_line =
                lambda2_cur.clone().square() - x_a_next.clone() - lambda1_cur.square() + x_p_cur;
```

Non-blocking: We should also make the `x_a_cur` elimination simplification in the Sinsemilla gate (which I think is what would remove the need for an `x_r` helper). This should happen in a separate PR.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs [hunk 25]
```diff
@@ -0,0 +1,296 @@
...
+            // Q is point at infinity
+            || (x_a == pallas::Base::zero() && y_a == pallas::Base::zero())
+            // x_p = x_a
+            || (x_p == x_a)
+            {
+                return Err(Error::SynthesisError);
+            }
+        }
+
+        // Enable `q_mul` on all but the last row of the incomplete range.
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul/incomplete.rs:198]: Yep, disabling this on the last row means we aren't constraining the `y_A` output of this `double_and_add`.

**Review by str4d — COMMENTED** [review]
Partial review of first 3 commits (I haven't looked at `complete.rs` yet).

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 26]
```diff
@@ -0,0 +1,427 @@
...
+
+        // Initialize the accumulator `acc = [2]base`
+        let acc = self
+            .add_config
+            .assign_region(&base, &base, offset, region)?;
+
+        // Increase the offset by 1 after complete addition.
+        let offset = offset + 1;
+
+        // Initialize the running sum for scalar decomposition to zero
```
[the remark this answers is not in the document]
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul.rs]: Now that I'm checking the initialised `y_a`, I'll need to use an extra cell on this row.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs [hunk 27]
```diff
@@ -0,0 +1,418 @@
...
+
+                // λ_{1,i}⋅(x_{A,i} − x_{P,i}) − y_{A,i} + (2k_i - 1) y_{P,i} = 0
+                let poly1 = lambda1_cur * (x_a_cur.clone() - x_p_cur) - y_a_cur.clone()
+                    + (k * pallas::Base::from_u64(2) - one.clone()) * y_p_cur;
+
+                // λ_{2,i}^2 − x_{A,i-1} − x_{R,i} − x_{A,i} = 0
+                let secant_line = lambda2_cur.clone().square()
+                    - x_a_next.clone()
+                    - x_r(meta, Rotation::cur())
+                    - x_a_cur.clone();
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul/incomplete.rs:178]: @ebfull is there any benefit to simplifying custom gates manually (eliminating `x_a_cur` here)? And/or can that simplification be done later if necessary, or automated, without changing `PinnedVerificationKey`?

**Review by str4d — COMMENTED** [review]
Flushing comments.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs (hunk 24 above)
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul/incomplete.rs]: I will make a book PR for that.

Comment (daira) [reply src/circuit/gadget/ecc/chip/mul/incomplete.rs]: Is this what you meant? https://hackmd.io/iOw7-HpFQY6dPF1aFY8pAw?both#Optimized-Sinsemilla-gate

Note that there is still a reference to x_{A,i} in each step.

Comment (daira) [reply src/circuit/gadget/ecc/chip/mul/incomplete.rs]: We established that this doesn't improve performance because x<sub>R,i</sub> still needs to be computed for Y<sub>A,i</sub>. (It's possible to save one addition by defining a temporary as λ<sub>1,i</sub><sup>2</sup> - x<sub>P,i</sub> but that's neither here nor there; we should take the simpler option and avoid changes at this stage.)

File: src/circuit/gadget/ecc/chip.rs [hunk 28]
```diff
@@ -176,18 +213,114 @@ impl EccChip {
...
+}
+
+/// A base field element used for fixed-base scalar multiplication.
+/// This is decomposed into 3-bit windows in little-endian order
+/// using a running sum `z`, where z_{i+1} = (z_i - a_i) / (2^3)
+/// for element α = a_0 + (2^3) a_1 + ... + (2^{3(n-1)}) a_{n-1}.
+/// Each `a_i` is in the range [0..2^3).
+///
+/// `windows` = [z_1, ..., z_85], where we expect z_85 = 0.
+/// Since z_0 is initialized as α, we store it as `base_field_elem`.
```
Comment (daira) [inline src/circuit/gadget/ecc/chip.rs:303]:
```suggestion
/// Since z_0 is initialized as the scalar α, we store it as `base_field_elem`.
```

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 29]
```diff
@@ -0,0 +1,251 @@
...
+        // [0]B should return (0,0) since it uses complete addition
+        // on the last step.
+        {
+            let scalar_fixed = pallas::Scalar::zero();
+            let scalar_fixed = ScalarFixedShort::new(
+                chip.clone(),
+                layouter.namespace(|| "ScalarFixedShort"),
+                Some(scalar_fixed),
+            )?;
+            value_commit_v.mul(layouter.namespace(|| "mul"), &scalar_fixed)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/short.rs:191]: Check the result.

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 30]
```diff
@@ -0,0 +1,251 @@
...
+            .enable(region, offset + NUM_WINDOWS)?;
+
+        // Assign final `x, y` to `x_p, y_p` columns and return final point
+        let x_val = magnitude_mul.x.value();
+        let x_var = region.assign_advice(
+            || "x_var",
+            self.super_config.x_p,
+            offset + NUM_WINDOWS,
+            || x_val.ok_or(Error::SynthesisError),
+        )?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/short.rs:116]: Blocking: This cell isn't constrained to equal `magnitude_mul.x`. However, AFAICT we don't actually need to assign it, since we can just return `magnitude_mul.x` (this is the end of the overall region, we don't need the output to be in a specific column).
```suggestion
        // Assign final `y` to `y_p` column, and return final point.
```

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 31]
```diff
@@ -0,0 +1,251 @@
...
+        let y_var = region.assign_advice(
+            || "y_var",
+            self.super_config.y_p,
+            offset + NUM_WINDOWS,
+            || y_val.ok_or(Error::SynthesisError),
+        )?;
+
+        let result = EccPoint {
+            x: CellValue::new(x_var, x_val),
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/short.rs:125]:
```suggestion
            x: magnitude_mul.x,
```

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 32]
```diff
@@ -0,0 +1,580 @@
...
+                acc + (window_pow.clone() * meta.query_fixed(*coeff, Rotation::cur()))
+            },
+        );
+
+        // Check interpolation of x-coordinate
+        let x_check = interpolated_x - x_p;
+        // Check that `y + z = u^2`, where `z` is fixed and `u`, `y` are witnessed
+        let y_check = u.clone() * u - y_p - z;
+
+        vec![toggle.clone() * x_check, toggle * y_check]
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:180]: Blocking: Unless it's somewhere else, this is missing the on-curve check:
```suggestion
        // Check interpolation of x-coordinate
        let x_check = interpolated_x - x_p.clone();
        // Check that `y + z = u^2`, where `z` is fixed and `u`, `y` are witnessed
        let y_check = u.square() - y_p.clone() - z;
        // Check that (x, y) is on the curve
        let on_curve = y_p.square() - x_p.clone().square() * x_p - 5;

        std::array::IntoIter::new([
            ("check x", x_check),
            ("check y", y_check),
            ("on-curve", on_curve),
        ]).map(move |(name, poly)| (name, toggle.clone() * poly))
```
(I don't remember if there's a constant for `b` in `pasta_curves`.)

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 33]
```diff
@@ -0,0 +1,580 @@
...
+        // Process all windows excluding least and most significant windows
+        let acc = self.add_incomplete(region, offset, acc, base, scalar)?;
+
+        // Process most significant window using complete addition
+        let mul_b = self.process_msb(region, offset, base, scalar)?;
+
+        Ok((acc, mul_b))
+    }
+
+    fn assign_fixed_constants(
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:207]: I got up to here.

**Review by str4d — COMMENTED** [review]
The only files I haven't reviewed are:
- `src/circuit/gadget/ecc/chip/mul_fixed.rs` (started)
- `src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs`

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 34]
```diff
@@ -0,0 +1,185 @@
...
+        base: FixedPoint<pallas::Affine, EccChip>,
+    ) -> Result<(), Error>
+    where
+        pallas::Scalar: PrimeFieldBits,
+    {
+        // [a]B
+        {
+            let scalar_fixed = pallas::Scalar::rand();
+
+            let scalar_fixed = ScalarFixed::new(
```
[the remark this answers is not in the document]
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:141]: Let's do this rename in the Action circuit PR.

File: src/circuit/gadget/ecc/chip.rs [hunk 35]
```diff
@@ -176,18 +213,115 @@ impl EccChip {
...
+    magnitude: Option<pallas::Scalar>,
+    sign: CellValue<pallas::Base>,
+    windows: ArrayVec<CellValue<pallas::Base>, { constants::NUM_WINDOWS_SHORT }>,
+}
+
+/// A base field element used for fixed-base scalar multiplication.
+/// This is decomposed into 3-bit windows in little-endian order
+/// using a running sum `z`, where z_{i+1} = (z_i - a_i) / (2^3)
+/// for element α = a_0 + (2^3) a_1 + ... + (2^{3(n-1)}) a_{n-1}.
+/// Each `a_i` is in the range [0..2^3).
```
Comment (daira) [inline src/circuit/gadget/ecc/chip.rs:300]: This also applies to the comment above (which is confusing because that's the comment that will be read first).

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 36]
```diff
@@ -0,0 +1,484 @@
+use super::{add, CellValue, EccConfig, EccPoint, EccScalarVar, Var};
+use crate::{
+    circuit::gadget::utilities::copy,
+    constants::{NUM_COMPLETE_BITS, T_Q},
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:4]: If `NUM_COMPLETE_BITS` is not used in other files, just move it to this one.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 37]
```diff
@@ -0,0 +1,484 @@
...
+const INCOMPLETE_LEN: usize = pallas::Scalar::NUM_BITS as usize - 1 - NUM_COMPLETE_BITS;
+const INCOMPLETE_RANGE: Range<usize> = 0..INCOMPLETE_LEN;
+
+// Bits k_{254} to k_{4} inclusive are used in incomplete addition.
+// The `hi` half is k_{254} to k_{130} inclusive (length 125 bits).
+const INCOMPLETE_HI_RANGE: Range<usize> = 0..(INCOMPLETE_LEN / 2);
+
+// Bits k_{254} to k_{4} inclusive are used in incomplete addition.
+// The `lo` half is k_{129} to k_{4} inclusive (length 126 bits).
+const INCOMPLETE_LO_RANGE: Range<usize> = (INCOMPLETE_LEN / 2)..INCOMPLETE_LEN;
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:33]: Add a static assertion that the boundary is at 130, i.e. that `INCOMPLETE_LO_RANGE.len() + 1 + NUM_COMPLETE_BITS == 130`.

Comment (daira) [reply src/circuit/gadget/ecc/chip/mul.rs:33]: Add a link to the book here.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 38]
```diff
@@ -0,0 +1,484 @@
...
+mod complete;
+mod incomplete;
+mod overflow;
+
+// Bits used in incomplete addition. k_{254} to k_{4} inclusive
+const INCOMPLETE_LEN: usize = pallas::Scalar::NUM_BITS as usize - 1 - NUM_COMPLETE_BITS;
+const INCOMPLETE_RANGE: Range<usize> = 0..INCOMPLETE_LEN;
+
+// Bits k_{254} to k_{4} inclusive are used in incomplete addition.
+// The `hi` half is k_{254} to k_{130} inclusive (length 125 bits).
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:28]:
```suggestion
// The `hi` half is k_{254} to k_{130} inclusive (length 125 bits).
// (It is a coincidence that k_{130} matches the boundary of the
// overflow check described in <ref book>.)
```

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 39]
```diff
@@ -0,0 +1,484 @@
...
+            //    z_0 = 2 * z_1 + k_0
+            // => k_0 = z_0 - 2 * z_1
+            let lsb = z_0 - z_1 * pallas::Base::from_u64(2);
+            let one_minus_lsb = Expression::Constant(pallas::Base::one()) - lsb.clone();
+
+            let bool_check = lsb.clone() * one_minus_lsb.clone();
+
+            // `lsb` = 0 => (x_p, y_p) = (x, -y)
+            // `lsb` = 1 => (x_p, y_p) = (0,0)
+            let lsb_x = (lsb.clone() * x_p.clone()) + one_minus_lsb.clone() * (x_p - base_x);
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:116]: We can expand this as ```
  lsb * x_p + (1 - lsb) * x_p - (1 - lsb) * base_x
= x_p - (1 - lsb) * base_x
```

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 40]
```diff
@@ -0,0 +1,484 @@
...
+            let lsb_y = (lsb * y_p.clone()) + one_minus_lsb * (y_p + base_y);
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:117]:
```
  lsb * y_p + (1 - lsb) * y_p + (1 - lsb) * base_y
= y_p + (1 - lsb) * base_y
```

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 41]
```diff
@@ -188,7 +182,8 @@ pub mod tests {
                 layouter.namespace(|| "ScalarFixedShort"),
                 Some(scalar_fixed),
             )?;
-            value_commit_v.mul(layouter.namespace(|| "mul"), &scalar_fixed)?;
+            let result = value_commit_v.mul(layouter.namespace(|| "mul by zero"), &scalar_fixed)?;
+            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), &zero)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/short.rs:186]:
```suggestion
            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), zero)?;
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 42]
```diff
@@ -269,6 +270,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "commit_ivk_r"),
             commit_ivk_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:273]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 43]
```diff
@@ -278,6 +280,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "note_commit_r"),
             note_commit_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:283]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 44]
```diff
@@ -287,6 +290,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "nullifier_k"),
             nullifier_k,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:293]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 45]
```diff
@@ -296,12 +300,18 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "value_commit_r"),
             value_commit_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:303]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 46]
```diff
@@ -296,12 +300,18 @@ pub mod tests {
...
 
         // spend_auth_g
         let spend_auth_g = OrchardFixedBasesFull::SpendAuthG;
         let spend_auth_g = FixedPoint::from_inner(chip.clone(), spend_auth_g);
-        test_single_base(chip, layouter.namespace(|| "spend_auth_g"), spend_auth_g)?;
+        test_single_base(
+            chip,
+            layouter.namespace(|| "spend_auth_g"),
+            spend_auth_g,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:313]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 47]
```diff
@@ -356,7 +367,9 @@ pub mod tests {
                 column,
                 Some(scalar_fixed),
             )?;
-            base.mul_base_field_elem(layouter.namespace(|| "mul by zero"), scalar_fixed)?;
+            let result =
+                base.mul_base_field_elem(layouter.namespace(|| "mul by zero"), scalar_fixed)?;
+            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), &zero)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:372]:
```suggestion
            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), zero)?;
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 48]
```diff
@@ -77,6 +78,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "commit_ivk_r"),
             commit_ivk_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:81]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 49]
```diff
@@ -86,6 +88,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "note_commit_r"),
             note_commit_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:91]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 50]
```diff
@@ -95,6 +98,7 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "nullifier_k"),
             nullifier_k,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:101]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 51]
```diff
@@ -104,12 +108,18 @@ pub mod tests {
             chip.clone(),
             layouter.namespace(|| "value_commit_r"),
             value_commit_r,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:111]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 52]
```diff
@@ -104,12 +108,18 @@ pub mod tests {
...
 
         // spend_auth_g
         let spend_auth_g = OrchardFixedBasesFull::SpendAuthG;
         let spend_auth_g = FixedPoint::from_inner(chip.clone(), spend_auth_g);
-        test_single_base(chip, layouter.namespace(|| "spend_auth_g"), spend_auth_g)?;
+        test_single_base(
+            chip,
+            layouter.namespace(|| "spend_auth_g"),
+            spend_auth_g,
+            &zero,
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:121]:
```suggestion
            zero,
```

File: src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs [hunk 53]
```diff
@@ -166,7 +177,8 @@ pub mod tests {
                 layouter.namespace(|| "ScalarFixed"),
                 Some(scalar_fixed),
             )?;
-            base.mul(layouter.namespace(|| "mul by zero"), &scalar_fixed)?;
+            let result = base.mul(layouter.namespace(|| "mul by zero"), &scalar_fixed)?;
+            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), &zero)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs:181]:
```suggestion
            result.constrain_equal(layouter.namespace(|| "[0]B = 𝒪"), zero)?;
```

**Review by str4d — COMMENTED** [review]
Clippy lints

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 54]
```diff
@@ -0,0 +1,644 @@
...
+
+        // Decompose the base field element α into three-bit windows
+        // using a running sum `z`, where z_{i+1} = (z_i - a_i) / (2^3)
+        // for α = a_0 + (2^3) a_1 + ... + (2^{3(84)}) a_{84}.
+        //
+        // We set z_0 = α, which implies:
+        //      z_1 = (α - a_0) / 2^3, (subtract the lowest 3 bits)
+        //          = a_1 + (2^3) a_2 + ... + 2^{3(83)} a_{84},
+        //      z_2 = (z_1 - a_1) / 2^3
+        //          = a_2 + (2^3) a_3 + ... + 2^{3(82)} a_{84},
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:67]:
```suggestion
        // for α = a_0 + (2^3) a_1 + ... + (2^{3*84}) a_{84}.
        //
        // We set z_0 = α, which implies:
        //      z_1 = (α - a_0) / 2^3, (subtract the lowest 3 bits)
        //          = a_1 + (2^3) a_2 + ... + 2^{3*83} a_{84},
        //      z_2 = (z_1 - a_1) / 2^3
        //          = a_2 + (2^3) a_3 + ... + 2^{3*82} a_{84},
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 55]
```diff
@@ -0,0 +1,644 @@
...
+            );
+        }
+
+        config
+    }
+}
+
+impl Config {
+    pub fn create_gate(&self, meta: &mut ConstraintSystem<pallas::Base>) {
+        // Check that an expression is in the range [0..range),
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:51]:
```suggestion
        // Check that an expression is in the small range [0..range),
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 56]
```diff
@@ -0,0 +1,644 @@
...
+        // This gate also checks that this window uses the correct y_p and
+        // interpolated x_p.
+        meta.create_gate("Decompose base field element", |meta| {
+            let base_field_fixed_mul = meta.query_selector(self.base_field_fixed_mul);
+
+            let z_cur = meta.query_advice(self.super_config.window, Rotation::cur());
+            let z_next = meta.query_advice(self.super_config.window, Rotation::next());
+
+            //    z_{i+1} = (z_i - a_i) / (2^3)
+            // => a_i = z_i - (z_{i+1} * (2^3))
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:85]:
```suggestion
            //    z_{i+1} = (z_i - a_i) / (2^3)
            // => a_i = z_i - z_{i+1} * 2^3
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 57]
```diff
@@ -0,0 +1,644 @@
...
+        meta.create_gate("Canonicity checks", |meta| {
+            let base_field_fixed_canon = meta.query_selector(self.base_field_fixed_canon);
+
+            let alpha = meta.query_advice(self.canon_advices[0], Rotation::prev());
+            // z_85_alpha is constrained to be zero in this gate.
+            let z_85_alpha = meta.query_advice(self.canon_advices[1], Rotation::prev());
+            // The last three bits of α.
+            let z_84_alpha = meta.query_advice(self.canon_advices[2], Rotation::prev());
+
+            // Decompose α into three pieces,
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:111]:
```suggestion
            // Decompose α into three pieces, in little-endian order:
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 58]
```diff
@@ -0,0 +1,644 @@
...
+            };
+
+            // We want to enforce canonicity of a 255-bit base field element, α.
+            // That is, we want to check that 0 ≤ α < p, where p is Pallas base
+            // field modulus p = 2^254 + t_p
+            //                 = 2^254 + 45560315531419706090280762371685220353.
+            // Note that t_p < 2^130.
+            //
+            // α has been decomposed into three pieces,
+            //            α = α_0 (252 bits)  || α_1 (2 bits) || α_2 (1 bit).
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:156]:
```suggestion
            // α has been decomposed into three pieces in little-endian order:
            //            α = α_0 (252 bits) || α_1 (2 bits) || α_2 (1 bit)
            //              = α_0 + 2^{252} α_1 + 2^{254} α_2
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 59]
```diff
@@ -0,0 +1,644 @@
...
+            let z_13_alpha_0 = meta.query_advice(self.canon_advices[2], Rotation::next());
+
+            let decomposition_checks = {
+                // Range-constrain α_1 to be 2 bits
+                let alpha_1_range_check = range_check(alpha_1.clone(), 1 << 2);
+                // Boolean-constrain α_2
+                let alpha_2_range_check = range_check(alpha_2.clone(), 1 << 1);
+                // Check that α_1 + 2^2 α_2 = z_84_alpha
+                let z_84_alpha_check = z_84_alpha.clone()
+                    - (alpha_1 + alpha_2.clone() * pallas::Base::from_u64(1 << 2));
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:129]:
```suggestion
                    - (alpha_1.clone() + alpha_2.clone() * pallas::Base::from_u64(1 << 2));
```
(we end up needing `alpha_1` again below).

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 60]
```diff
@@ -0,0 +1,644 @@
...
+            //      - α_2 = 1 => α_1 = 0, and
+            //      - α_2 = 1 => α_0 < t_p. To enforce this:
+            //          - α_2 = 1 => 0 ≤ α_0 < 2^130
+            //                    => 13 ten-bit lookups of α_0
+            //          - α_2 = 1 => 0 ≤ α_0 + 2^130 - t_p < 2^130
+            //                    => 13 ten-bit lookups of α_0 + 2^130 - t_p
+            //                    => z_13_alpha_0_prime = 0
+            //
+            let canon_checks = {
+                std::iter::empty()
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:168]:
```suggestion
                std::iter::empty()
                    .chain(Some((
                        "MSB = 1 => alpha_1 = 0",
                        alpha_2.clone() * alpha_1,
                    )))
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 61]
```diff
@@ -0,0 +1,645 @@
...
+        )?;
+
+        // We want to enforce canonicity of a 255-bit base field element, α.
+        // That is, we want to check that 0 ≤ α < p, where p is Pallas base
+        // field modulus p = 2^254 + t_p
+        //                 = 2^254 + 45560315531419706090280762371685220353.
+        // Note that t_p < 2^130.
+        //
+        // α has been decomposed into three pieces,
+        //            α = α_0 (252 bits)  || α_1 (2 bits) || α_2 (1 bit).
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:251]:
```suggestion
            // α has been decomposed into three pieces in little-endian order:
            //            α = α_0 (252 bits) || α_1 (2 bits) || α_2 (1 bit)
            //              = α_0 + 2^{252} α_1 + 2^{254} α_2.
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 62]
```diff
@@ -0,0 +1,645 @@
...
+        //      z_1 = (α - a_0) / 2^3, (subtract the lowest 3 bits)
+        //          = a_1 + (2^3) a_2 + ... + 2^{3(83)} a_{84},
+        //      z_2 = (z_1 - a_1) / 2^3
+        //          = a_2 + (2^3) a_3 + ... + 2^{3(82)} a_{84},
+        //      ...,
+        //      z_{84} = a_{84}
+        //      z_n = (z_{84} - a_{84}) / 2^3
+        //          = 0.
+        //
+        // This gate checks that each a_i = z_i - z_{i+1} * (2^3) is within
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:73]:
```suggestion
        // for α = a_0 + 2^3 a_1 + ... + 2^{3*84} a_84.
        //
        // We set z_0 = α, which implies:
        //      z_1 = (α - a_0) / 2^3, (subtract the lowest 3 bits)
        //          = a_1 + 2^3 a_2 + ... + 2^{3*83} a_84,
        //      z_2 = (z_1 - a_1) / 2^3
        //          = a_2 + 2^3 a_3 + ... + 2^{3*82} a_84,
        //      ...,
        //      z_84 = a_84
        //      z_n = (z_84 - a_84) / 2^3
        //          = 0.
        //
        // This gate checks that each a_i = z_i - z_{i+1} * 2^3 is within
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 63]
```diff
@@ -0,0 +1,645 @@
...
+            let alpha_0 = alpha
+                .value()
+                .zip(z_84_alpha.value())
+                .map(|(alpha, z_84_alpha)| {
+                    let two_pow_252 = pallas::Base::from_u128(1 << 126).square();
+                    alpha - z_84_alpha * two_pow_252
+                });
+
+            let (alpha_0, zs) = self.lookup_config.witness_check(
+                layouter.namespace(|| "Lookup range check alpha + 2^130 - t_p"),
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:277]:
```suggestion
                layouter.namespace(|| "Lookup range check alpha"),
```
However, we should be able to use a similar trick to https://hackmd.io/o9EzZBwxSWSi08kQ_fMIOw?view#Overflow-check-for-variable-base-scalar-multiplication to enforce α ∊ [0, 2<sup>130</sup>) without an explicit 10-bit decomposition:

Note that 132 = 44 · 3. Also we have z<sub>44</sub> = a<sub>44</sub> + 2<sup>3</sup> a<sub>45</sub> + ... + 2<sup>3·(84-44)</sup> a<sub>84</sub>.
So the low 132 bits of α are zero exactly when α - 2<sup>44</sup> z<sub>44</sub> = 0. And then we can check that α ∊ [0, 2<sup>130</sup>) by checking α - 2<sup>44</sup> z<sub>44</sub> = 0 and a<sub>43</sub> ∊ {0, 1}.

File: src/circuit/gadget/utilities.rs [hunk 64]
```diff
@@ -84,3 +86,27 @@ where
 
     Ok(CellValue::new(cell, copy.value))
 }
+
+/// Subsets a field element to a specified bitrange (little-endian)
+pub fn bitrange_subset<F: FieldExt + PrimeFieldBits>(
+    field_elem: F,
+    bitrange: std::ops::Range<usize>,
+) -> F {
```
Comment (str4d) [inline src/circuit/gadget/utilities.rs:94]: Add some test cases for this.

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 65]
```diff
@@ -0,0 +1,645 @@
...
+                false,
+            )?;
+
+            (alpha_0, zs[13])
+        };
+
+        let (alpha_0_prime, z_13_alpha_0_prime) = {
+            // alpha_0_prime = alpha + 2^130 - t_p.
+            let alpha_0_prime = alpha_0.value().map(|alpha_0| {
+                let two_pow_130 = pallas::Base::from_u128(65).square();
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:289]: Ah, this is probably why tests pass: the bug is duplicated here.
```suggestion
                let two_pow_130 = pallas::Base::from_u128(1 << 65).square();
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 66]
```diff
@@ -0,0 +1,645 @@
...
+    ) -> Result<EccPoint, Error> {
+        let (result, scalar) = layouter.assign_region(
+            || "Base-field elem fixed-base mul",
+            |mut region| {
+                let offset = 0;
+
+                // Decompose scalar
+                let scalar = self.decompose_base_field_elem(scalar, offset, &mut region)?;
+
+                let (acc, mul_b) = self.super_config.assign_region_inner(
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:202]: How does this work? `decompose_base_field_elem` assigns a running sum into the `window` column, but `super_config.assign_region_inner` requires that this column contain the 3-bit words themselves, as it uses the cells directly to interpolate `x`.

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 67]
```diff
@@ -0,0 +1,645 @@
...
+        for (idx, word) in words.iter().enumerate() {
+            // z_next = (z_cur - word) / (2^3)
+            let z_next = {
+                let word = word.map(|word| pallas::Base::from_u64(word as u64));
+                let z_next_val = z
+                    .value()
+                    .zip(word)
+                    .map(|(z_cur_val, word)| (z_cur_val - word) * eight_inv);
+                let cell = region.assign_advice(
+                    || format!("word {:?}", idx),
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:477]: This is assigning the running sum, not the words:
```suggestion
                    || format!("z_{:?}", idx + 1),
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 68]
```diff
@@ -0,0 +1,645 @@
...
+        // [a]B
+        {
+            let scalar_fixed = pallas::Base::rand();
+            let scalar_fixed = chip.load_private(
+                layouter.namespace(|| "witness random base field element"),
+                column,
+                Some(scalar_fixed),
+            )?;
+
+            base.mul_base_field_elem(layouter.namespace(|| "mul"), scalar_fixed)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:594]: Check the result of this (by witnessing the expected result).

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 69]
```diff
@@ -0,0 +1,645 @@
...
+                            acc * &h + &pallas::Base::from_u64(c.to_digit(8).unwrap().into())
+                        });
+
+            let scalar_fixed = chip.load_private(
+                layouter.namespace(|| "mul with double"),
+                column,
+                Some(scalar_fixed),
+            )?;
+
+            base.mul_base_field_elem(layouter.namespace(|| "mul with double"), scalar_fixed)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:615]: Check the result of this (by witnessing the expected result).

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 70]
```diff
@@ -0,0 +1,645 @@
...
+
+        // [-1]B is the largest base field element
+        {
+            let scalar_fixed = -pallas::Base::one();
+            let scalar_fixed = chip.load_private(
+                layouter.namespace(|| "mul by -1"),
+                column,
+                Some(scalar_fixed),
+            )?;
+            base.mul_base_field_elem(layouter.namespace(|| "mul by -1"), scalar_fixed)?;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:640]: Check the result of this (by witnessing the expected result).

**Review by str4d — CHANGES_REQUESTED** [review]

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 71]
```diff
@@ -0,0 +1,583 @@
...
+            .iter()
+            .enumerate()
+        {
+            // Offset window index by 1 since we are starting on k_1
+            let w = w + 1;
+
+            // Compute [(k_w + 2) ⋅ 8^w]B
+            let mul_b = {
+                let mul_b = k.map(|k| {
+                    base_value * (k + pallas::Scalar::from_u64(2)) * h.pow(&[w as u64, 0, 0, 0])
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul_fixed.rs:396]: Alternatively, see zcash/pasta_curves#14

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 72]
```diff
@@ -0,0 +1,253 @@
...
+                self.super_config
+                    .copy_scalar(&mut region, offset, &scalar.into())?;
+
+                let (acc, mul_b) = self.super_config.assign_region_inner(
+                    &mut region,
+                    offset,
+                    &scalar.into(),
+                    base.clone().into(),
+                    self.super_config.q_mul_fixed,
+                )?;
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul_fixed/short.rs:75]: I suspect also that making the 6 columns be on the right would help with layout, since we have a lot of regions that use columns on the left. But we can tweak things like that after we've merged the Action circuit PR.

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 73]
```diff
@@ -0,0 +1,645 @@
...
+}
+
+impl Config {
+    pub fn create_gate(&self, meta: &mut ConstraintSystem<pallas::Base>) {
+        // Check that an expression is in the range [0..range),
+        // i.e. 0 ≤ word < range.
+        let range_check = |word: Expression<pallas::Base>, range: usize| {
+            (0..range).fold(Expression::Constant(pallas::Base::one()), |acc, i| {
+                acc * (word.clone() - Expression::Constant(pallas::Base::from_u64(i as u64)))
+            })
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:56]: I saw that, but I thought that the Expression evaluator would merge constants and suppress multiplication by 1. If it doesn't, perhaps it should.

[the remark this answers is not in the document]
Comment (str4d) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:56]: It does not.

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs (hunk 66 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:202]: This works because the `mul_fixed::Config::coords_check()` creates the gate that checks interpolation, and this helper takes in an expression for `window`.

In `base_field_elem::Config::create_gate()`, we input the expression 
```
word = z_cur - z_next * pallas::Base::from_u64(constants::H as u64);
```
as the "window" to the `coords_check()` helper.

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 74]
```diff
@@ -0,0 +1,645 @@
...
+                let alpha_1_range_check = range_check(alpha_1.clone(), 1 << 2);
+                // Boolean-constrain α_2
+                let alpha_2_range_check = range_check(alpha_2.clone(), 1 << 1);
+                // Check that α_1 + 2^2 α_2 = z_84_alpha
+                let z_84_alpha_check = z_84_alpha.clone()
+                    - (alpha_1.clone() + alpha_2.clone() * pallas::Base::from_u64(1 << 2));
+
+                // Check that the witnessed α_0 fulfils the constraint α_0 = α - z_84_alpha * 2^252
+                let two_pow_252 = pallas::Base::from_u128(1 << 126).square();
+                let expected_alpha_0 = alpha - (z_84_alpha * two_pow_252);
```
[the remark this answers is not in the document]
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:133]: I've now documented this constraint in the book: 4af23e62dca4fbd28c67adc3b1248f94584ea868

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs (hunk 63 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:277]: This optimisation makes sense to me, but I understand the details as being slightly different: the range check is on α<sub>0</sub> = α - 2<sup>3·(84)</sup> a<sub>84</sub> ∊ [0, 2<sup>130</sup>). 

To do this, we check:
- the high 120 bits of α<sub>0</sub> are all-zero, i.e. z<sub>44</sub> - 2<sup>3·(84 - 44)</sup> a<sub>84</sub> = 0. This constrains α<sub>0</sub> to be a 132-bit value.
- bits 130..=131 of α<sub>0</sub>, i.e. a<sub>43</sub> ∊ {0,1}. This constrains α<sub>0</sub> to be a 130-bit value.

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 75]
```diff
@@ -0,0 +1,583 @@
...
+        let base_u = base.u();
+        let scalar_windows_field = scalar.windows_field();
+        let scalar_windows_usize = scalar.windows_usize();
+
+        for (w, k) in scalar_windows_field[1..(scalar_windows_field.len() - 1)]
+            .iter()
+            .enumerate()
+        {
+            // Offset window index by 1 since we are starting on k_1
+            let w = w + 1;
```
[the remark this answers is not in the document]
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed.rs]: I've chosen the first alternative.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 76]
```diff
@@ -449,35 +453,97 @@ pub mod tests {
...
+        fn constrain_equal<
+            EccChip: EccInstructions<pallas::Affine> + Clone + Eq + std::fmt::Debug,
+        >(
+            chip: EccChip,
+            mut layouter: impl Layouter<pallas::Base>,
+            base_val: pallas::Affine,
+            scalar_val: pallas::Base,
+            result: Point<pallas::Affine, EccChip>,
+        ) -> Result<(), Error> {
+            // Case scalar from base field into scalar field
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul.rs:467]:
```suggestion
            // Move scalar from base field into scalar field (which always fits for Pallas).
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 77]
```diff
@@ -0,0 +1,679 @@
...
+            self.super_config.window,
+            offset,
+            &base_field_elem,
+            &self.super_config.perm,
+        )?;
+
+        for idx in 0..words.len() {
+            self.base_field_fixed_mul.enable(region, offset + idx)?;
+        }
+
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:462]: This causes the selector to be double-enabled, as it is also activated by the call to `self.super_config.assign_region_inner` above:

image
```suggestion
```

**Review by str4d — APPROVED** [review]
utACK ae4e54dce8b789c43ce3170f83bac8ebc734e12c. Test circuit LGTM other than the unnecessary double-assignment of `base_field_fixed_mul`.

[EDIT: Removed old chip layout as I can't seem to hide review comments. See below for latest.]

File: src/circuit/gadget/ecc/chip/mul.rs (hunk 19 above)
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul.rs:160]:
```suggestion
                    // Constrain the initialization of `z` to equal zero.
                    // TODO: use an equality constraint instead.
```

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 78]
```diff
@@ -0,0 +1,551 @@
...
+        let bitstring: Vec<bool> = {
+            let mut le_bytes = [0u8; 32];
+            k.to_little_endian(&mut le_bytes);
+            le_bytes.iter().fold(Vec::new(), |mut bitstring, byte| {
+                let bits = (0..8)
+                    .map(|shift| (byte >> shift) % 2 == 1)
+                    .collect::<Vec<_>>();
+                bitstring.extend_from_slice(&bits);
+                bitstring
+            })
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:427]: This should probably be a utility function. (Does not block.)

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 79]
```diff
@@ -0,0 +1,551 @@
...
+                chip,
+                layouter.namespace(|| "[-1]B"),
+                p_val,
+                scalar_val,
+                result,
+            )?;
+        }
+
+        Ok(())
+    }
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul.rs:550]: Test the case where the last step (the complete addition) is a doubling. I think this occurs for the scalar 0x1b6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6e; please check this.

File: src/circuit/gadget/ecc/chip/mul/complete.rs [hunk 80]
```diff
@@ -0,0 +1,186 @@
...
+            |meta| {
+                let q_mul_decompose_var = meta.query_selector(self.q_mul_decompose_var);
+                // z_{i + 1}
+                let z_prev = meta.query_advice(self.z_complete, Rotation::prev());
+                // z_i
+                let z_next = meta.query_advice(self.z_complete, Rotation::next());
+
+                // k_{i} = z_{i} - 2⋅z_{i+1}
+                let k = z_next - Expression::Constant(pallas::Base::from_u64(2)) * z_prev;
+                let k_minus_one = k.clone() - Expression::Constant(pallas::Base::one());
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul/complete.rs:59]: https://github.com/zcash/orchard/issues/143

File: src/circuit/gadget/ecc/chip/mul/complete.rs [hunk 81]
```diff
@@ -0,0 +1,186 @@
...
+                // (k_i) ⋅ (k_i - 1) = 0
+                let bool_check = k.clone() * k_minus_one.clone();
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/complete.rs:61]:
```suggestion
                // (k_i)^2 - k_i = 0
                let bool_check = k.clone().square() - k.clone();
```

File: src/circuit/gadget/ecc/chip/mul/complete.rs [hunk 82]
```diff
@@ -0,0 +1,186 @@
...
+
+                std::array::IntoIter::new([("bool_check", bool_check), ("y_switch", y_switch)])
+                    .map(move |(name, poly)| (name, q_mul_decompose_var.clone() * poly))
+            },
+        );
+    }
+
+    #[allow(clippy::type_complexity)]
+    #[allow(non_snake_case)]
+    #[allow(clippy::too_many_arguments)]
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/complete.rs:80]: Opinion: the default threshold of at most 7 arguments to avoid this lint is silly. We should raise that globally.

File: src/circuit/gadget/ecc/chip/mul/incomplete.rs [hunk 83]
```diff
@@ -0,0 +1,419 @@
...
+    fn from(ecc_config: &EccConfig) -> Self {
+        let config = Config {
+            num_bits: INCOMPLETE_HI_RANGE.len(),
+            q_mul: ecc_config.q_mul_hi,
+            x_p: ecc_config.advices[0],
+            y_p: ecc_config.advices[1],
+            z: ecc_config.advices[9],
+            x_a: ecc_config.advices[3],
+            lambda1: ecc_config.advices[4],
+            lambda2: ecc_config.advices[5],
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul/incomplete.rs:50]: What's the rationale for this ordering?

Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul/incomplete.rs:50]: The main rationale is that "hi_config z cannot overlap with complete addition columns", which is checked in an assertion in `mul.rs` (L86). Were it not for this requirement, we could have used a more natural ordering (e.g. [2], [3], [4], [5]).

Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul/incomplete.rs:50]: The rationale is to avoid an overlap with the output columns of complete addition, which are used to initialise the accumulator at 2[T]. This has now been explained at https://github.com/zcash/orchard/pull/111/commits/b696163e318d541f1327d851e2e9cb8f1b33287a.

File: src/circuit/gadget/ecc/chip/mul.rs (hunk 79 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul.rs:555]: I have checked that the last step is a doubling for 0x16db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6db6dc.

File: src/circuit/gadget/ecc/chip/mul.rs [hunk 84]
```diff
@@ -80,15 +80,20 @@ impl From<&EccConfig> for Config {
...
+        // z and lambda1 are assigned on the same row as the add_config output.
+        // Therefore, z and lambda1 must not overlap with add_config.x_qr, add_config.y_qr.
+        let add_config_outputs = config.add_config.output_columns();
+        for config in [&(*config.hi_config), &(*config.lo_config)].iter() {
+            assert!(
+                !add_config_outputs.contains(&config.z),
+                "incomplete config z cannot overlap with complete addition columns."
+            );
+            assert!(
+                !add_config_outputs.contains(&config.lambda1),
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul.rs:93]: This was previously checking `complete_config.z_complete`, and now it instead checks `{hi|lo}_config.lambda1`. Why is `z_complete` not necessary to check?

**Review by str4d — APPROVED** [review]
re-utACK b696163e318d541f1327d851e2e9cb8f1b33287a

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 85]
```diff
@@ -0,0 +1,529 @@
...
+                assert_eq!(NUM_WINDOWS, constants::NUM_WINDOWS_SHORT);
+                let base = ValueCommitV::get();
+                (
+                    base.lagrange_coeffs_short.0.as_ref().to_vec(),
+                    base.z_short.0.as_ref().to_vec(),
+                )
+            }
+            OrchardFixedBases::Full(base) => {
+                assert_eq!(NUM_WINDOWS, constants::NUM_WINDOWS);
+                let base: OrchardFixedBase = base.into();
```
[the remark this answers is not in the document]
Comment (daira) [reply src/circuit/gadget/ecc/chip/mul_fixed.rs:243]: Why aren't we building the constants in a lazy_static?

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 86]
```diff
@@ -0,0 +1,550 @@
...
+                scalar.windows_usize()[NUM_WINDOWS - 1].map(|k| base.u()[NUM_WINDOWS - 1].0[k]);
+            region.assign_advice(
+                || "u",
+                self.u,
+                offset + NUM_WINDOWS - 1,
+                || u_val.ok_or(Error::SynthesisError),
+            )?;
+        }
+
+        // offset_acc = \sum_{j = 0}^{NUM_WINDOWS - 2} 2^{FIXED_BASE_WINDOW_SIZE * j+1}
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:427]:
```suggestion
        // offset_acc = \sum_{j = 0}^{NUM_WINDOWS - 2} 2^{FIXED_BASE_WINDOW_SIZE*j + 1}
```

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 87]
```diff
@@ -0,0 +1,550 @@
...
+        let offset_acc = (0..(NUM_WINDOWS - 1)).fold(pallas::Scalar::zero(), |acc, w| {
+            acc + (*TWO_SCALAR).pow(&[
+                constants::FIXED_BASE_WINDOW_SIZE as u64 * w as u64 + 1,
+                0,
+                0,
+                0,
+            ])
+        });
+
+        // `scalar = [k * 8^84 - offset_acc]`, where `offset_acc = \sum_{j = 0}^{83} 2^{FIXED_BASE_WINDOW_SIZE * j + 1}`.
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:437]:
```suggestion
        // `scalar = [k * 8^84 - offset_acc]`, where `offset_acc = \sum_{j = 0}^{83} 2^{FIXED_BASE_WINDOW_SIZE*j + 1}`.
```

File: src/circuit/gadget/ecc/chip/mul.rs (hunk 84 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul.rs:93]: The `z_complete` check was being duplicated. It was (and still is) checked in `mul::complete.rs`.

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 88]
```diff
@@ -0,0 +1,550 @@
...
+
+    // The scalar decomposition is guaranteed to be in three-bit windows,
+    // so we also cast the least significant byte in their serialisation
+    // into usize for convenient indexing into `u`-values
+    fn windows_usize(&self) -> Vec<Option<usize>> {
+        self.windows_field()
+            .iter()
+            .map(|window| {
+                if let Some(window) = window {
+                    let window = window.to_bytes()[0] as usize;
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:541]:
```suggestion
                    let window = window.get_lower_32() as usize;
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs [hunk 89]
```diff
@@ -0,0 +1,676 @@
...
+        Ok(())
+    }
+
+    #[allow(clippy::op_ref)]
+    fn test_single_base(
+        chip: EccChip,
+        mut layouter: impl Layouter<pallas::Base>,
+        base: FixedPoint<pallas::Affine, EccChip>,
+        base_val: pallas::Affine,
+    ) -> Result<(), Error> {
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:572]: Why do these tests seem to be duplicated here and in `mul_fixed/full_width.rs`?

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs [hunk 90]
```diff
@@ -0,0 +1,317 @@
...
+                layouter.namespace(|| "[-2^64 - 1]B"),
+                base_val,
+                scalar_fixed_short,
+                result,
+            )?;
+        }
+
+        // There is a single canonical sequence of window values for which a doubling occurs on the last step:
+        // 1333333333333333333334 in octal.
+        // [0xB6DB_6DB6_DB6D_B6DC] B
```
Comment (daira) [inline src/circuit/gadget/ecc/chip/mul_fixed/short.rs:291]: Test this value with both signs.

File: src/circuit/gadget/utilities.rs [hunk 91]
```diff
@@ -97,3 +98,195 @@ pub fn transpose_option_array<T: Copy + std::fmt::Debug, const LEN: usize>(
     }
     ret
 }
+
+/// Subsets a field element to a specified bitrange (little-endian)
```
Comment (daira) [inline src/circuit/gadget/utilities.rs:102]: It was unclear to me what this meant without looking at the implementation. I suggest something like:
```suggestion
/// Takes a specified subsequence of the little-endian bit representation of a field element.
```

File: src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs (hunk 89 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs:572]: They're duplicated because the `mul_fixed()` and `mul_fixed_base_field_elem()` are both usable with the same set of fixed points. Perhaps we could abstract these tests out?

File: src/circuit/gadget/ecc/chip/mul_fixed/short.rs (hunk 90 above)
Comment (therealyingtong) [reply src/circuit/gadget/ecc/chip/mul_fixed/short.rs:291]: Since these tests are refactored in #145, I have noted this comment there and will address it in that PR: https://github.com/zcash/orchard/pull/145/files#r670057072

File: src/constants.rs [hunk 92]
```diff
@@ -20,6 +20,14 @@ pub mod util;
 
 pub use load::{OrchardFixedBase, OrchardFixedBasesFull, ValueCommitV};
 
+/// The Pallas scalar field modulus is $q = 2^{254} + \mathsf{t_q}$.
+/// <https://github.com/zcash/pasta>
+pub(crate) const T_Q: u128 = 45560315531506369815346746415080538113;
+
+/// The Pallas base field modulus is $p = 2^{254} + \mathsf{t_p}$.
+/// <https://github.com/zcash/pasta>
+pub(crate) const T_P: u128 = 45560315531419706090280762371685220353;
```
Comment (daira) [inline src/constants.rs:29]: I checked these values.

**Review by daira — APPROVED** [review]
utACK with minor comments.

File: src/circuit/gadget/ecc/chip/mul_fixed.rs [hunk 93]
```diff
@@ -531,14 +531,14 @@ impl ScalarFixed {
...
-    // so we also cast the least significant byte in their serialisation
+    // so we also cast the least significant 4 bytes in their serialisation
     // into usize for convenient indexing into `u`-values
     fn windows_usize(&self) -> Vec<Option<usize>> {
         self.windows_field()
             .iter()
             .map(|window| {
                 if let Some(window) = window {
-                    let window = window.to_bytes()[0] as usize;
+                    let window = window.get_lower_32() as usize;
```
Comment (str4d) [inline src/circuit/gadget/ecc/chip/mul_fixed.rs:541]: @daira left a comment inside the `get_lower_32()` impls:
> // TODO: don't reduce, just hash the Montgomery form. (Requires rebuilding perfect hash table.)

We'll need to take care over there to ensure we don't alter this API, now that we are relying on it outside the perfect hash table.

**Review by str4d — APPROVED** [review]
re-utACK 425ee6e038d4104cbbb0804c76714ab067b1d8f5. Test chip LGTM.

ecc-chip-layout
